baseURL = "https://cstaaben.github.io/"
languageCode = "en-us"
title = "Corbin Staaben"
theme = "hugo-profile"
Paginate = 3.0
enableRobotsTXT = true
disqusShortname = "cstaaben-github-io"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
home = [
  "HTML",
  "RSS",
  "JSON"
]
page = [
  "HTML",
  "RSS"
]

[markup]

  [markup.goldmark]

    [markup.goldmark.renderer]
    unsafe = true

[Menus]

  [[Menus.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog posts"
  url = "/blogs"
  weight = 1.0

  # [[Menus.main]]
  # identifier = "gallery"
  # name = "Gallery"
  # title = "Blog posts"
  # url = "/gallery"
  # weight = 2.0

[params]
title = "Corbin Staaben"
description = "Random thoughts and projects I'm working on."
favicon = "/fav.png"
useBootstrapCDN = false
animate = false

  # [params.theme]
  # disableThemeToggle = true
  # defaultTheme = "dark"

  # [params.color]
  #   textColor = "#F5F5F5"
  #   secondaryTextColor = "#F5F5F5"
  #   backgroundColor = "#313552"
  #   primaryColor = "#F1E0AC"
  #   secondaryColor = "#30475E"
    # [[params.color.darkmode]]
      #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  [params.font]
  fontSize = "1rem"
  fontWeight = 400.0
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Corbin Staaben"
  disableSearch = false

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = true
    disableAchievements = true
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Corbin."
  subtitle = "I build software and design systems."
  content = "A constantly learning engineer. I write software that prioritizes maintainability and TDD. I dabble in DevOps and game development."
  # image = "/images/software_engineer_1.svg"
  image = "/images/attributed_developer.svg"


    [params.hero.button]
    enable = true
    name = "Resume"
    url = "Resume.pdf"
    download = true
    newPage = false

    [params.hero.socialLinks]

      [[params.hero.socialLinks.fontAwesomeIcons]]
      icon = "fab fa-github"
      url = "https://github.com/cstaaben"

  [params.about]
  enable = true
  title = "About Me"
  image = "/images/mugshot.png"
#  content = "I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. \n\nI am currently working on a project that will be used to help people find the best way to get around the city."
  content = "I am a software engineer with a constant desire to learn and push my boundaries. I have a background in computer science, with an emphasis on software engineering, and I have an interest in game development (particularly procedurally generated content) and the principles of DevOps. I am currently working at [Kochava](https://www.kochava.com) as a senior software engineer.\n\nI am currently working on a project to automate compliance with GDPR and CCPA."

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = [
      "Go / Golang",
      "PHP",
      "MySQL / MariaDB",
      "PostgreSQL",
      "Kubernetes",
      "Pub/Sub",
      "Kafka",
      "Vue.js",
      "Google BigQuery",
      "NoSQL Databases",
    ]

  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "Senior Software Engineer"
    company = "Kochava"
    companyUrl = "https://kochava.com"
    date = "Nov 2022 - present"
    content = "I am currently working as a senior software engineer on the Product team at [Kochava](https://kochava.com). My current project is automating compliance with GDPR and CCPA. \n\nThe only reason for this title change is a re-org of the engineering teams and the application of an official career ladder. My responsibilities did not change much between this position and my time as Lead Software Engineer.\n\nMy primary responsibilities include: \n- Critical-priority work\n- Onboarding new hires and interns\n- Mentoring junior team members\n- Designing and writing primarily customer-facing systems and projects\n- Writing documentation for legacy systems to prevent tribal knowledge\n- Holding team members and other teams accountable to follow documentation standards"

      # [params.experience.items.featuredLink]
      # enable = false
      # name = "View the project"
      # url = "https://example.com"

    [[params.experience.items]]
    job = "Lead Software Engineer"
    company = "Kochava"
    companyUrl = "https://kochava.com"
    date = "July 2020 - Nov 2022"
    content = "I was a Lead Software Engineer on the Solutions & Integrations team. My primary responsibilities included:\n- Critical-priority work\n- Onboarding new hires and interns\n- Mentoring junior team members\n- Designing and writing primarily customer-facing systems and projects.\n- Setting and enforcing code standards and best practices in code reviews\n- Working with other engineering teams to develop documentation standards"

      # [params.experience.items.featuredLink]
      # enable = false
      # url = "https://example.com"
      #
      # [params.experience.items.info]
      # enable = false
      # content = "I worked as a software developer for more than one year in Amazon."

    [[params.experience.items]]
    job = "Senior Software Engineer"
    company = "Kochava"
    companyUrl = "https://kochava.com"
    date = "July 2019 - July 2020"
    content = "My primary responsibility as a Senior Software Engineer on the Solutions & Integrations team was to tackle the highest priority tasks from our client success team and integrations team and mentor junior members of the team. I assisted with onboarding, but was not a driving force of the onboarding schedule. Some of the things I worked on were:\n- REST APIs\n- Data pipelines\n- ETL processes\n- CLI / Internal tools to handle oncall situations"

      # [params.experience.items.info]
      # enable = false
      #
      # [params.experience.items.featuredLink]
      # enable = false

    [[params.experience.items]]
    job = "Software Engineer"
    company = "Kochava"
    companyUrl = "https://kochava.com"
    date = "April 2017 - July 2019"
    content = "As a software engineer, my primary responsibilities were handling tickets that were assigned to me or I deemed were within (or near enough) my ability to solve. These tickets primarily came from our client success team and were things broken or missing from our products. I dove into"

      # [params.experience.items.featuredLink]
      # enable = false
      # url = "https://example.com"

  [params.education]
  enable = true
  index = false

    [[params.education.items]]
    title = "Bachelolor of Science in Computer Science"
    date = "2012 - 2017"
    # GPA = "3.8 out of 5.0"
    # content = "Extracurricular Activities\n  - Lorem ipsum dolor sit amet consectetur adipisicing elit. \n  - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique."

      [params.education.items.school]
      name = "Eastern Washington University"
      url = "https://www.ewu.edu/"

    # [[params.education.items]]
    # title = "Bachelor of Science in Computer Science"
    # date = "2009 - 2013"
    # GPA = "3.9 out of 5.0"
    # content = "I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.\n- [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)\n- Face mask detection using a single convolutional neural network.\n\nExtracurricular Activities\n  - Lorem ipsum dolor sit amet consectetur adipisicing elit. \n  - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique."
    #
    #   [params.education.items.school]
    #   name = "Massachusetts Institute of Technology"
    #   url = "https://example.org"
    #
    #   [params.education.items.featuredLink]
    #   enable = true
    #   name = "My academic record"
    #   url = "https://example.com"
    #
    # [[params.education.items]]
    # title = "High School"
    # GPA = "4.2 out of 5.0"
    #
    #   [params.education.items.school]
    #   name = "Thomas Jefferson High School for Science and Technology."
    #   url = "https://example.org"
    #
    #   [params.education.items.featuredLink]
    #   enable = true
    #   url = "https://example.com"

  [params.achievements]
  enable = false

    # [[params.achievements.items]]
    # title = "Google kickstart runner"
    # content = "I solved all problems with optimal solution."
    # url = "https://example.com"
    #
    # [[params.achievements.items]]
    # title = "Facebook Hackathon Winner"
    # content = "Developed a product using Artificial Intelligence."
    #
    # [[params.achievements.items]]
    # title = "Hugo Profile"
    # content = "Developed a theme and getting 1K+ downloads per month."
    # url = "https://github.com/gurusabarish/hugo-profile"
    #
    # [[params.achievements.items]]
    # title = "Microsoft Imagine Runner"
    # content = "We are developed a product which can help others."
    #
    # [[params.achievements.items]]
    # title = "Google Summer of Code"
    # content = "Contributed to a open source project."
    # url = "https://example.com"

  [params.projects]
  enable = false

    [[params.projects.items]]
    title = "Hugo Profile"
    content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
    image = "/images/projects/profile.png"
    badges = [
      "Hugo",
      "Bootstrap",
      "Javascript"
    ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://hugo-profile.netlify.app"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/hugo-profile"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Image Converter"
    content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
    image = "/images/projects/converter.jpg"
    badges = [
      "Django",
      "Bootstrap"
    ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://django-converter.herokuapp.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Hugo Profile V2"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "/images/projects/profile2.jpg"
    badges = [
      "Hugo",
      "Bootstrap",
      "Javascript"
    ]

      [params.projects.items.featured]
      name = "Demo V2"
      link = "https://hugo-profile-2.netlify.app"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you."
  email = "cstaaben@gmail.com"
  btnName = "Mail me"

  [params.footer]

    [params.footer.recentPosts]
    path = "blogs"
    count = 3.0
    title = "Recent Posts"
    enable = true
    disableFeaturedImage = false

    [params.footer.socialNetworks]
    github = "https://github.com/cstaaben"
    linkedin = "https://www.linkedin.com/in/corbin-staaben-529569129/"
    # twitter = "https://twitter.com"
    # instagram = "https://instagram.com"
    # facebook = "https://facebook.com"

  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]

    [params.singlePages.readTime]
    enable = true
    content = "min read"
